name: SonarCloud analysis

on:
  push:
    branches: [ "main", dev, staging, feature/** ]
  pull_request:
    branches:  [ "main", dev, staging, ]
  workflow_dispatch:
permissions:
  pull-requests: read
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: |
            npm install --force
      # - name: Run Coverage
      #   shell: bash
      #   run: |
      #     npm run coverage && npm run coverage:report
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
